

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/demo
    driver-class-name: org.h2.Driver
    password:
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:file:secrets.yaml
      # this to import secrets from separate files
#jwt:
#  secret: uZ8x+5f2Cez+ZPVujVKK1ZQ06JNuqRXtQ2Ojft9mK+0=